## NOTE: Requires Istio CRDs (VirtualService, DestinationRule).
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productcatalogservice-destination
spec:
  host: productcatalogservice
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v3
    labels:
      version: v3

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productcatalogservice-vs
spec:
  hosts:
  - productcatalogservice
  http:
  - match:
    - headers:
        x-canary-test:
          exact: v3
    route:
    - destination:
        host: productcatalogservice
        subset: v3
      weight: 100
  - route:
    - destination:
        host: productcatalogservice
        subset: v1
      weight: 80
    - destination:
        host: productcatalogservice
        subset: v3
      weight: 20

# Component `with-canary-rollback`: sends 20% of traffic to v3 (v1/v3 only).
