apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus.monitoring.svc.cluster.local:9090
        access: proxy
        isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  node-dashboard.json: |
    {
      "id": null,
      "title": "Node Resource Usage",
      "timezone": "browser",
      "schemaVersion": 16,
      "version": 1,
      "panels": [
        {
          "type": "graph",
          "title": "Node CPU Usage",
          "targets": [
            {
              "expr": "100 - (avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
              "legendFormat": "{{instance}}"
            }
          ]
        },
        {
          "type": "graph",
          "title": "Node Memory Usage",
          "targets": [
            {
              "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
              "legendFormat": "{{instance}}"
            }
          ]
        },
        {
          "type": "graph",
          "title": "Node Disk Usage",
          "targets": [
            {
              "expr": "100 * (1 - (node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay\"} / node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"}))",
              "legendFormat": "{{instance}} - {{mountpoint}}"
            }
          ]
        },
        {
          "type": "graph",
          "title": "Node Network I/O",
          "targets": [
            {
              "expr": "rate(node_network_receive_bytes_total[5m])",
              "legendFormat": "{{instance}} - receive"
            },
            {
              "expr": "rate(node_network_transmit_bytes_total[5m])",
              "legendFormat": "{{instance}} - transmit"
            }
          ]
        }
      ]
    }
  pod-dashboard.json: |
    {
      "id": null,
      "title": "Pod Resource Usage",
      "timezone": "browser",
      "schemaVersion": 16,
      "version": 1,
      "panels": [
        {
          "type": "graph",
          "title": "Pod CPU Usage",
          "targets": [
            {
              "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=\"default\", container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_pod_name!=\"\"}[5m])) by (container_label_io_kubernetes_pod_namespace, container_label_io_kubernetes_pod_name)",
              "legendFormat": "{{container_label_io_kubernetes_pod_namespace}} / {{container_label_io_kubernetes_pod_name}}"
            }
          ]
        },
        {
          "type": "graph",
          "title": "Pod Memory Usage",
          "targets": [
            {
              "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_namespace=\"default\", container_label_io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_pod_name!=\"\"}) by (container_label_io_kubernetes_pod_namespace, container_label_io_kubernetes_pod_name)",
              "legendFormat": "{{container_label_io_kubernetes_pod_namespace}} / {{container_label_io_kubernetes_pod_name}}"
            }
          ]
        },
        {
          "type": "graph",
          "title": "Pod Network I/O",
          "targets": [
            {
              "expr": "sum(rate(container_network_receive_bytes_total{container_label_io_kubernetes_pod_namespace=\"default\", container_label_io_kubernetes_pod_name!=\"\"}[5m])) by (container_label_io_kubernetes_pod_namespace, container_label_io_kubernetes_pod_name)",
              "legendFormat": "{{container_label_io_kubernetes_pod_namespace}} / {{container_label_io_kubernetes_pod_name}} - receive"
            },
            {
              "expr": "sum(rate(container_network_transmit_bytes_total{container_label_io_kubernetes_pod_namespace=\"default\", container_label_io_kubernetes_pod_name!=\"\"}[5m])) by (container_label_io_kubernetes_pod_namespace, container_label_io_kubernetes_pod_name)",
              "legendFormat": "{{container_label_io_kubernetes_pod_namespace}} / {{container_label_io_kubernetes_pod_name}} - transmit"
            }
          ]
        }
      ]
    }
  redis-dashboard.json: |
    {
      "id": null,
      "title": "Redis Cart Metrics",
      "timezone": "browser",
      "schemaVersion": 16,
      "version": 1,
      "panels": [
        {
          "type": "stat",
          "title": "Redis Cart Status",
          "targets": [{ "expr": "redis_up{job=\"redis-cart-exporter\"}", "legendFormat": "Status (1=Up)" }]
        },
        {
          "type": "graph",
          "title": "Commands Per Second",
          "targets": [{ "expr": "rate(redis_commands_processed_total{job=\"redis-cart-exporter\"}[1m])", "legendFormat": "ops/sec" }]
        },
        {
          "type": "graph",
          "title": "Memory Usage",
          "targets": [
            { "expr": "redis_memory_used_bytes{job=\"redis-cart-exporter\"}", "legendFormat": "Used Memory" },
            { "expr": "redis_memory_max_bytes{job=\"redis-cart-exporter\"}", "legendFormat": "Max Limit" }
          ]
        },
        {
          "type": "graph",
          "title": "Connected Clients",
          "targets": [{ "expr": "redis_connected_clients{job=\"redis-cart-exporter\"}", "legendFormat": "Clients" }]
        },
        {
          "type": "graph",
          "title": "Keys in Database",
          "targets": [{ "expr": "redis_db_keys{job=\"redis-cart-exporter\"}", "legendFormat": "Keys - {{db}}" }]
        },
        {
          "type": "graph",
          "title": "Evicted Keys",
          "targets": [{ "expr": "rate(redis_evicted_keys_total{job=\"redis-cart-exporter\"}[5m])", "legendFormat": "Evictions/sec" }]
        },
        {
          "type": "graph",
          "title": "Cache Hit Rate",
          "targets": [{ "expr": "rate(redis_keyspace_hits_total{job=\"redis-cart-exporter\"}[5m]) / (rate(redis_keyspace_hits_total{job=\"redis-cart-exporter\"}[5m]) + rate(redis_keyspace_misses_total{job=\"redis-cart-exporter\"}[5m])) * 100", "legendFormat": "Hit Rate %" }]
        }
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-providers
  namespace: monitoring
data:
  providers.yaml: |
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: Default
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "512Mi"
          volumeMounts:
            - name: datasource
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
            - name: dashboards-providers
              mountPath: /etc/grafana/provisioning/dashboards
      volumes:
        - name: datasource
          configMap:
            name: grafana-datasource
        - name: dashboards
          configMap:
            name: grafana-dashboards
        - name: dashboards-providers
          configMap:
            name: grafana-dashboard-providers
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
